import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body className={inter.className}>
        <Providers> {/* Provider is a client component, but it won't make everything inside as client components */}
          {children} {/* Server components can be passed as props, but we can't import a server component in side a 'use client' as it will make it client side render */}
        </Providers>
      </body>
    </html>
  );
}
